export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const FETCH_QUESTIONS_ATTEMPT = "FETCH_QUESTIONS_ATTEMPT";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
